extends SceneTree

## Write every virtual method Godot declares to tools/engine_virtuals.txt.
##
## `check_dead_declarations.py` needs it: a virtual override has no caller
## anywhere in this repo, because the engine is the caller, and without this list
## the guard would report `_ready` and forty others as dead on the first run.
##
## Regenerate after a Godot upgrade:
##
##     godot --headless --path . -s tools/dump_engine_virtuals.gd

const OUT_PATH := "res://tools/engine_virtuals.txt"


func _init():
	var names := {}
	for cls in ClassDB.get_class_list():
		for method in ClassDB.class_get_method_list(cls, true):
			var flags: int = method.get("flags", 0)
			if flags & METHOD_FLAG_VIRTUAL == 0:
				continue
			var method_name: String = str(method.get("name", ""))
			if method_name.begins_with("_"):
				names[method_name] = true
	var sorted: Array = names.keys()
	sorted.sort()
	var file := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("dump_engine_virtuals: cannot write %s" % OUT_PATH)
		quit(1)
		return
	file.store_line("# Generated by tools/dump_engine_virtuals.gd. Do not hand edit.")
	file.store_line("# Godot %s" % Engine.get_version_info().get("string", "unknown"))
	for method_name in sorted:
		file.store_line(method_name)
	file.close()
	print("wrote %d virtuals to %s" % [sorted.size(), OUT_PATH])
	quit()
